### ISSUE TITLE
case (event, state)

### ISSUE THREAD

**Issue by OlivierChirouze** [dohzya/scalaio-2017-esmonad#1]
Hi!

I read your slides again after Scala.io 2017: I liked your presentation a lot but it was a bit too fast for me when you presented it live ;-)
Starting at slide 35, I have the feeling you inverted `event` and `state` as parameters of the last `case`: I believe it should be `case (state, event)` instead of `case (event, state)`.

The only impact is of course that the printed message will be incorrect as it will print "Invalid event _the state_ for state _the event_"... not a big deal.

Thanks for the talk anyway, very instructing!

**Comment by dohzya** [comment]
Thank you a lot! 🙌

About the presentation, we feared that we wouldn't have enough time to finish, so we talked too fast indeed 🙁 We need to work on that 🙂

Nice catch, I just pushed 1c6c27258 which should fix the handlers 😉

**Comment by OlivierChirouze** [comment]
Thanks!
About the talk, I guess it depends on the audience: I'm not so familiar with the concepts discussed during the talk so it was hard for me to catch up, but with more experienced audience I guess this was a proper pace ;-)

**Comment by dohzya** [comment]
Oh, so we failed a bit: a goal of the talk was to introduce to some high-level concepts using real-world examples (well… neither mathematical nor “let's see how this function could be rewritten”)

Feel free to ask any questions you could have 😉
